# Message when Enderpearl is throwing in restricted zone :
message : "§c>> Enderpearling not allow here !"


zones:
  world:
    min: [0, 0, 0]
    max: [50, 50, 50]
  world2:
    min: [20, 10, 20]
    max: [70, 30, 70]

# Add zones as you want
# WorldName :
#  min: [x, y, z]
#  max: [x, y, z]
#
